version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'